### ISSUE TITLE
Reading variant of the InCell 2000 format

### ISSUE THREAD

**Issue by sbesson** [IDR/idr0061-wolf-spindlepositioning#2]
The imaging data associated with this submission has been generated by the IN Cell Analyzer 2200 instrument. The data is a plate where each well sample is a single-channel timelapse image.

While some of the plates read correctly, others fail reader initialization with

```
build@ae95b4b9604e:~$ /bio-formats-build/bioformats/tools/showinf -nopix /data/20190403-ftp/BSF014270/New/New_1/New_1.xdce 
Checking file format [InCell 1000/2000]
Initializing reader
InCellReader initializing /data/20190403-ftp/BSF014270/New/New_1/New_1.xdce
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at loci.formats.in.InCellReader$MinimalInCellHandler.startElement(InCellReader.java:870)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at loci.common.xml.XMLTools.parseXML(XMLTools.java:551)
	at loci.common.xml.XMLTools.parseXML(XMLTools.java:533)
	at loci.formats.in.InCellReader.initFile(InCellReader.java:378)
	at loci.formats.FormatReader.setId(FormatReader.java:1389)
	at loci.formats.ImageReader.setId(ImageReader.java:843)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
```

From https://github.com/openmicroscopy/bioformats/blob/a28a7cb6e7aa07862dc5a788720ff8032a51fd2e/components/formats-gpl/src/loci/formats/in/InCellReader.java#L870, the issue lies with the expectation that the imaging data has too channels

```
        <Wavelengths>
            <Wavelength aperture_rows="50" fusion_wave="false" imaging_mode="2-D" index="0" label="" laser_power
="100" open_aperture="true" show="false" z_section="0.0" z_slice="1" z_step="0.0">
                <ExcitationFilter name="TL-Brightfield" unit="nm" wavelength="595"/>
                <EmissionFilter name="Cy3" unit="nm" wavelength="597"/>
                <Exposure time="100.0" unit="ms"/>
                <HWAFOffset unit="?m" value="0.0"/>
                <FocusOffset unit="?m" value="-48.0"/>
                <FusionData/>
            </Wavelength>
            <Wavelength aperture_rows="50" fusion_wave="false" imaging_mode="2-D" index="1" label="" laser_power
="100" open_aperture="true" show="false" z_section="0.0" z_slice="1" z_step="0.0">
                <ExcitationFilter name="TexasRed" unit="nm" wavelength="575"/>
                <EmissionFilter name="TexasRed" unit="nm" wavelength="620"/>
                <Polychroic name="QUAD3"/>
                <Exposure time="100.0" unit="ms"/>
                <HWAFOffset unit="?m" value="0.0"/>
                <FocusOffset unit="?m" value="-15.0"/>
                <FusionData/>
            </Wavelength>
        </Wavelengths>
```

Most images declared in the metadata XML file are referring to channel 0 although a handful of them are referring to channel 1:

```
build@ae95b4b9604e:~$ grep 'wave_index="0"' /data/20190403-ftp/BSF014270/New/New_1/New_1.xdce  | wc
  34752  208512 3488448
build@ae95b4b9604e:~$ grep 'wave_index="1"' /data/20190403-ftp/BSF014270/New/New_1/New_1.xdce  | wc
    192    1152   19008
```

Sample dataset: `/uod/idr/filesets/idr0061-wolf-spindlepositioning/20190403-ftp/BSF014270/`

**Comment by melissalinkert** [comment]
Looking at ```New/New_1/New_1.xdce```, 34944 planes are defined (one per ```Image``` element).  The first 384 of these (96 wells x 2 fields x 2 channels) do not actually exist on disk at all, but are consistent with the plate/timepoint/channel metadata at the beginning of the file.  The remaining 34560 match up with the 34560 TIFF files, and correspond to 96 wells x 2 fields x 180 timepoints, which is not consistent with the metadata at the beginning of the file.

As far as I can see, the only way to distinguish between the two sets is using the ```filename``` attribute on the ```Image``` and checking for existence.  It's unclear to me from the .xdce file why there are effectively two plate acquisitions here, why the files for the first one are missing, why the metadata for the second one are missing, and how this all should be correctly represented.

The most straightforward thing to do is probably to pre-scan the ```Image``` elements to find the max ```*_index``` values (ignoring anything where the ```filename``` does not exist), instead of relying upon the rest of the metadata in the file.  This would result in one plate with 96 wells x 2 fields x 180 timepoints corresponding to the real files.  It would be good to have confirmation that those are the expected dimensions before making any code changes, though.  Happy to discuss if needed.

**Comment by sbesson** [comment]
Thanks for the feedback. Following some interactions with the submitters, they confirmed the extra 384 planes were not supposed to be there in the first place. New `xcde` files have been submitted removing the unnecesary `<Image>` and `<Wavelength>` elements.

Now the metadata files are consistent with the files on disk, the reader still throws an exception e.g. using the same dataset under `/uod/idr/filesets/idr0061-wolf-spindlepositioning/20190403-ftp/BSF014270/New/New_1/`

```
build@86c2d611c8ef:/bio-formats-build$ /bio-formats-build/bioformats/tools/showinf -nopix /data/BSF014270.xdce 
Checking file format [InCell 1000/2000]
Initializing reader
InCellReader initializing /data/BSF014270.xdce
Reading IFDs
Populating metadata
Unknown ExperimentType value 'Fluorescence' will be stored as "Other"
Exception in thread "main" java.lang.IllegalArgumentException: -1 must be neither null nor strictly negative.
	at ome.xml.model.primitives.NonNegativeInteger.<init>(NonNegativeInteger.java:48)
	at loci.formats.in.InCellReader.initFile(InCellReader.java:614)
	at loci.formats.FormatReader.setId(FormatReader.java:1389)
	at loci.formats.ImageReader.setId(ImageReader.java:843)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
```

**Comment by melissalinkert** [comment]
Line 35534 of ```BSF014270.xdce``` still has the original plane count:

```
   <Images image_format="TIFF" number="34944" path="Y:\Benita\2015_March_L_Screen_2ndRound\WDH\BSF014720\Pre\New\New_1" version="1.0">
```

which throws off all of the plane indexing.  https://github.com/openmicroscopy/bioformats/pull/3383 should fix it.

**Comment by sbesson** [comment]
Thanks, retested after updating the `number` attribute of the `Images` element to match the number of `Image` elements. The HCS plate now reads, imports and render as expected

![Screen Shot 2019-05-31 at 16 11 25](https://user-images.githubusercontent.com/1355463/58715436-c265ff00-83be-11e9-9e72-50bafae97035.png)

#1 has been modified to 1- modify the `Images` attribute and 2- copy the modified `xdce` files in the right location. If this imports successfully in a testing resource, we can close this issue as resolved.
